apiVersion: v1
kind: Secret
metadata:
  name: users-db-secret
  namespace: {{ include "food-ordering.namespace" . }}
  labels:
    {{- include "food-ordering.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: jdbc:postgresql://users-db:5432/users_db
  username: users_user
  password: users_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-db-secret
  namespace: {{ include "food-ordering.namespace" . }}
  labels:
    {{- include "food-ordering.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: jdbc:postgresql://orders-db:5432/orders_db
  username: orders_user
  password: orders_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
  namespace: {{ include "food-ordering.namespace" . }}
  labels:
    {{- include "food-ordering.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: jdbc:postgresql://catalog-db:5432/catalog_db
  username: catalog_user
  password: catalog_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: payments-db-secret
  namespace: {{ include "food-ordering.namespace" . }}
  labels:
    {{- include "food-ordering.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: jdbc:postgresql://payments-db:5432/payments_db
  username: payments_user
  password: payments_pass
---
apiVersion: v1
kind: Secret
metadata:
  name: deliveries-db-secret
  namespace: {{ include "food-ordering.namespace" . }}
  labels:
    {{- include "food-ordering.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: jdbc:postgresql://deliveries-db:5432/deliveries_db
  username: deliveries_user
  password: deliveries_pass
