replicaCount: 2
image:
  repository: food-ordering/deliveries-service
  tag: latest
service:
  port: 8085
  type: ClusterIP
database:
  secretName: deliveries-db-secret
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 70
