apiVersion: v1
kind: Service
metadata:
  name: {{ include "payments-service.fullname" . }}
  namespace: {{ .Values.global.namespace | default "food-ordering" }}
  labels:
    {{- include "payments-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "payments-service.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type | default "ClusterIP" }}
