apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  namespace: {{ .Values.global.namespace | default "food-ordering" }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type | default "LoadBalancer" }}
